### ISSUE TITLE
Issues targeted for 5.0

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#4495]
The following issues are required to be completed for 5.0 release:

- [x] #4297 Revisit oauth2 module structure

- [x] #4553 Re-structure OAuth2AuthenticationToken
- [x] #4520 OAuth2AuthenticationToken.ClientRegistration -> AuthorizedClient
- [x] #4521 Introduce OIDC Client and User Authentication
- [x] #4554 Move additionalParameters to TokenResponseAttributes
- [x] #4522 Remove OAuth2AuthenticationToken.AccessToken

- [x] #4447 Split up NimbusOAuth2UserService
- [x] #4451 Retrieving the UserInfo should be optional
- [x] #4547 Upgrade Nimbus dependencies

- [x] #4575 ClientRegistration.clientAlias -> registrationId
- [x] #4576 AuthorizationCodeAuthenticationProcessingFilter -> favor query request matching
- [x] #4581 Remove ProviderJwtDecoderRegistry

- [x] #4589 ClientRegistration Support baseUrl in template

- [x] #4513 Authorization Code Grant flow should support AccessToken only
- [x] #4590 Extract Validation/Authentication Logic in AuthorizationCodeAuthenticationProcessingFilter
- [x] #4500 Provide support for implicit grant
- [x] #4570 LoginPage for OAuth2

- [x] #4606 Externalize error codes from OAuth2Error
- [x] #4614 Remove Package Tangles
- [x] #4595 Consider renaming spring-security-jwt-jose
- [x] #4627 Getting NotSerializableExceptio when use spring-security-oauth2-client and spring-session together

- [x] #4440 Ensure ID Token Validation
- [x] #4441 Verify UserInfoResponse sub claim with IDToken sub claim
- [ ] #4442 Consider adding nonce to Authentication Request

- [ ] #4406 Provide oauth2Login sample for PWS

- [ ] #4298 Add unit tests to oauth2-core
- [ ] #4299 Add unit tests to oauth2-client
- [ ] #4494 Create migration guide

**Comment by adolfoweloy** [comment]
@jgrandja, as per the Spring Security 5.0.0 M1 release blog post, the initial support would be  primarily focused on the OAuth Client role.
I would like to know if there is any backlog data about OAuth Server roles (Authorization Server and Resource Server).

**Comment by jgrandja** [comment]
@adolfoweloy We are planning a 5.1 release not too far after the 5.0 release which will provide the Resource Server role functionality. The Authorization Server role functionality will follow that but will be a much bigger undertaking and therefore require more time and effort before that is released.

**Comment by adolfoweloy** [comment]
@jgrandja I have written a personal solution for `spring-security-oauth2` use case to generate JWE access tokens using Nimbus library. I would like to know if it would help creating a Pull Request for `spring-security-oauth2` (I didn't try it because of `spring-security-oauth2` being in maintenance mode and limited for new features).

**Comment by adolfoweloy** [comment]
@jgrandja I have cloned `spring-security-oauth` project and as I am exploring it I am creating some issues (some features that I think that would add value to this project regarding more specific scenarios with JWT and PoP (RFC 7800)). 

I would like to know if I could share these issues here or on `spring-security-oauth` (or none of these projects as well). And of course, if I could help with some contribution with code I would appreciate.

**Comment by jgrandja** [comment]
@adolfoweloy We are only focusing on bug fixes and minor improvements for the `spring-security-oauth` project and are limiting new features. If these issues can be merged without breaking any of the public API's that I can take a look at it.

However, our efforts are primarily focused on the new OAuth/OIDC support we're building into Spring Security 5. We always welcome contributions so please feel free especially with the new OAuth/OIDC support.

**Comment by duergner** [comment]
@jgrandja is there already a issue list / feature spec for the ResourceServer part you are planning on the 5.1 release? I would be really interested in having a look there and see whether this is something I (and maybe some colleagues) can contribute to.

**Comment by jgrandja** [comment]
@duergner I haven't started planning the Resource Server features for 5.1 as of yet. I'll definitely keep you in the loop when I start the planning which should be in about 3-4 weeks time. And that would be great if you can help contribute as well. Will ping you when I start logging issues. Thanks!
