### ISSUE TITLE
First class test support for spring-security-oauth2-client

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4833]
### Summary

We should add first-class test support for the spring-security-oauth2-client module

- [x] #7618 - Add OIDC Login MockMvc Test Support
- [x] #7680 - Add OIDC Login Reactive Test Support
- [x] #7789 - Add OAuth 2.0 Login MockMvc Test Support
- [x] #7828 - Add OAuth 2.0 Login Reactive Test Support
- [x] #7886 - Add OAuth 2.0 Client MockMvc Test Support
- [x] #7910 - Add OAuth 2.0 Client Reactive Test Support

**Comment by ch4mpy** [comment]
I may have the beginning of solution. 
[More details](https://github.com/spring-projects/spring-security/issues/6557#issuecomment-469232209)

**Comment by elch78** [comment]
Added another ticket that also relates to test support #7624

**Comment by jgrandja** [comment]
@jzheaux I know you were involved in helping merge some of the `oauth2-client` test support. Can this be closed now?

**Comment by jzheaux** [comment]
Yes @jgrandja, this was solved in #7618, #7680, #7789, #7828, #7886 and #7910. I've added those to the description for clarity.
