### ISSUE TITLE
Allow configurable HTTP client for oauth2-client flows

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#5601]
We need to provide the capability for user's to configure the underlying HTTP client used in the various `oauth2-client` flows. For example, the user may need to set custom parameters and/or headers in the request to the `/oauth2/token` endpoint.

Providing a `setRestOperations(restOperations)` method in the classes that implement the specific `oauth2-client` flows should meet this requirement.

The tasks below compromise the `oauth2-client` flows:

- [x] #5600 - Allow configurable RestOperations for DefaultOAuth2UserService
- [x] #5602 - Allow configurable RestOperations for CustomUserTypesOAuth2UserService
- [x] #5547 - Add RestOperations implementation of OAuth2AccessTokenResponseClient
- [x] #5603 - Allow configurable RestOperations for NimbusJwtDecoderJwkSupport
- [ ] #5607 - Register RestOperations `@Bean` to be used as default for oauth2-client flows

**Comment by jgrandja** [comment]
Closing this as all tasks but except #5607 are resolved.
