### ISSUE TITLE
Support Resource Owner Password Credentials grant

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#6003]
We need to provide support for the [Resource Owner Password Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.3).

This issue is divided into the following tasks.

### Servlet

- [x] [#31](https://github.com/spring-projects/spring-security-team-tasks/issues/31) Add password `OAuth2AccessTokenResponseClient`
- [x] [#32](https://github.com/spring-projects/spring-security-team-tasks/issues/32) Implement password `OAuth2AuthorizedClientProvider`

### Reactive

- [x] [#102](https://github.com/spring-projects/spring-security-team-tasks/issues/102) Add password `ReactiveOAuth2AccessTokenResponseClient`
- [x] [#103](https://github.com/spring-projects/spring-security-team-tasks/issues/103) Implement password `ReactiveOAuth2AuthorizedClientProvider`

**Comment by alwyn** [comment]
@jgrandja have you got any ideas on how you plan to implement this?

I am in need of this and looking at coding it, but I'm new to framework internals and oauth2, so currently I'm just following breadcrumbs and maybe naively basing it on client credentials.

**Comment by jgrandja** [comment]
Thanks for reaching out @alwyn. This feature will be implemented in `ServletOAuth2AuthorizedClientExchangeFilterFunction` and `ServerOAuth2AuthorizedClientExchangeFilterFunction`. However, depending on the outcome of the re-factoring exercise in #6811 , it may be implemented in a separate `ExchangeFilterFunction`. I plan on working on #6811 this coming week and after that is merged than we can start looking at implementing Resource Owner Password Grant feature. As an FYI, this will definitely get into 5.2.
