### ISSUE TITLE
Remove Servlet Spec 2.5 and 3.0 support

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6220]
The Spring Framework [baseline](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#baseline-update) moved to Servlet Spec 3.1 as of 5.x. This means that Spring Security can drop support for Servlet Spec 2.5 and 3.0.

Note that this is tangentially related to #6025 since some of Spring Security's PowerMock usage surrounds mocking a Servlet Spec 2.5 and 3.0 runtimes.

- [x] https://github.com/spring-projects/spring-security/issues/6259 Remove Session Fixation Servlet 2.5 Support
- [x] https://github.com/spring-projects/spring-security/issues/6260 Remove SecurityContextHolderAwareRequestFilter's Servlet 2.5 Support
- [x] https://github.com/spring-projects/spring-security/issues/6261 Remove HttpSessionSecurityContextRepository's Servlet 2.5 Support
- [x] https://github.com/spring-projects/spring-security/issues/6262 Remove Csrf Servlet 2.5 and 3.0 Support
- [x] https://github.com/spring-projects/spring-security/issues/6263 Remove Remember Me Servlet 2.5 and 3.0 Support
- [x] https://github.com/spring-projects/spring-security/issues/6264 Remove AbstractRequestMatcherRegistry's Servlet 3.0 Support
- [x] https://github.com/spring-projects/spring-security/issues/6265 Remove CacheControlHeadersWriter's Servlet 3.0 Support

**Comment by raphaelDL** [comment]
How do we approach this?

**Comment by jzheaux** [comment]
@raphaelDL Since it manifests itself in a few different features, I'll create some subtasks that are each targeted at an individual feature. I think that will result in completing this with greater confidence.
