### ISSUE TITLE
Use AuthorizationManager

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#9290]
With the introduction of `AuthorizationManager`, there are a number of next steps that seem valuable.

- [ ] Add AuthorizationDecision to AuthorizationFailureEvent - #9286
- [ ] Add Reasons to AuthorizationDecisions - #9287 
- [ ] DelegatingAuthorizationManager Should Fire Events - #9288 
- [ ] Consider AuthorizationManager for Method Security - #9289
- [ ] Refactor WebSocket Security to use AuthorizationManager
- [ ] Consider ReactiveAuthorizationManager for Reactive Method Security

Not yet included in this list are potential deprecations, though I think this could depend on where #9289 lands.
