### ISSUE TITLE
Update Spring Security build to require JDK 11

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#9419]
The latest OpenSAML major version (4.x) requires JDK 11, and the earlier OpenSAML version (3.x) has reached its end of life. In order to complete #9095, it is required to build with JDK 11.

To update to JDK 11 will require the following:

- [x] Migrate LDAP samples to use UnboundIdContainer - #9414
- [x] Remove `javax.annotation` usage - #9415
- [x] Rework LDAP ApacheDS tests to work with JDK 11 - #9416
- [x] Update Git workflows to use JDK 11 - #9417
- [x] Update community guidelines to require JDK 11 - #9418
- [x] R2dbcReactiveOAuth2AuthorizedClientServiceTests should anticipate a lower-precision timestamp - #9449 
- [x] OAuth2AuthenticationTokenMixinTests should anticipate a lower-precision timestamp - #9461
