### ISSUE TITLE
Documentation should point to spring-security-samples

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#9784]
In 5.5, `gh-samples-url` points to `https://github.com/spring-projects/spring-security/tree/5.5.0/samples`, but the samples have moved to `spring-security-samples`, so the links are broken.

The documentation should be updated in the following way:

- [x] Add messaging to documentation about sample migration #9815
- [x] Update links to point to migrated samples #9816
- [x] Remove links that point to unmigrated samples #9817
- [x] Consider adding a link checker to build #9818
- [x] Include samples in build #9846
- [x] Fix broken links in docs #9869
